### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [patvdv/check_health#1]
Hello, @patvdv  I like to contribute to open source software and i designed a  logo for check_health. If you like it, please write a comment here. I can send a pr. Also  can update the readme file.

![hc](https://user-images.githubusercontent.com/36298335/42412255-4befa3e4-8211-11e8-949d-862b1e0e4b3f.jpg)

**Comment by patvdv** [comment]
Hello, thank you very much for the contribution. I already the logo on the homepage. Let me know what kind of credit you would like to be added for your artwork.

**Comment by reallinfo** [comment]
oh, thanks :) Could you tell which one you like? I will load all necessary files(png-svg-horizontal-vertical-lgomark-editable file.) into the repository. Also, i will update the readme file.

**Comment by reallinfo** [comment]
If you ask me this color is the best.

![1](https://user-images.githubusercontent.com/36298335/42412679-a5673a1a-8219-11e8-846e-d2fd2b8373d4.jpg)

**Comment by patvdv** [comment]
Hi, I like the red/green one best! Could you make a final version and add it to the repo?

**Comment by reallinfo** [comment]
Sure, ı added the logo and i updated the readme file.

https://github.com/patvdv/check_health/pull/2

**Comment by patvdv** [comment]
Great stuff :+1: It looks awesome! Thanks again.

**Comment by reallinfo** [comment]
yo're welcome!
